using System;

namespace Throw {
    class Program {
        static void Main(string[] args) {
            throw new AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA();
        }
    }
}
class B {

}
internal class AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA : ApplicationException {
    public String A = "123";
}
class A {

}


// 3VWVGZR3SHPPV2IJVO0WMCDU1HBREJFU .Netfx 4.5
// 3VWVGZR3SHPPV2IJVO0WMCDU1HBREJFU .Netfx 4.0
// 3VWVGZR3SHPPV2IJVO0WMCDU1HBREJFU AsmVer 1.1
// 3VWVGZR3SHPPV2IJVO0WMCDU1HBREJFU Company A
// 3VWVGZR3SHPPV2IJVO0WMCDU1HBREJFU FileVer 1.2
// 3VWVGZR3SHPPV2IJVO0WMCDU1HBREJFU SystemException
// F3TKVMYXEZOZLEX31OJIZUGQJKRHIVX5 Throw.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
// 3VWVGZR3SHPPV2IJVO0WMCDU1HBREJFU public String A = "123";
// 3VWVGZR3SHPPV2IJVO0WMCDU1HBREJFU ThrowA
// 3VWVGZR3SHPPV2IJVO0WMCDU1HBREJFU .Netfx 2.0
// 3VWVGZR3SHPPV2IJVO0WMCDU1HBREJFU
// 3VWVGZR3SHPPV2IJVO0WMCDU1HBREJFU internal class AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 
// 1GLOAXWZ4H2LYXVXVGJLVU1DSGXBBUCN aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
